spring.application.name=Alphalytics

server.port=8080

# Configuration H2
spring.datasource.url=jdbc:h2:mem:alphalytics
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 (vizualise DB in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
